-- Chapter 2: SQL in Snowflake
--
-- Create a writable training copy of Snowflake's small TPC-H sample data set.
--
-- This script is safe to run again: existing tables are left untouched.
-- To start over, explicitly drop the SQL_IN_SNOWFLAKE database first.

CREATE DATABASE IF NOT EXISTS SQL_IN_SNOWFLAKE;
CREATE SCHEMA IF NOT EXISTS SQL_IN_SNOWFLAKE.TPCH;

USE DATABASE SQL_IN_SNOWFLAKE;
USE SCHEMA TPCH;

-- Dimension tables
CREATE TABLE IF NOT EXISTS REGION AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;

CREATE TABLE IF NOT EXISTS NATION AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

CREATE TABLE IF NOT EXISTS SUPPLIER AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;

CREATE TABLE IF NOT EXISTS CUSTOMER AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

CREATE TABLE IF NOT EXISTS PART AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

-- Relationship and transaction tables
CREATE TABLE IF NOT EXISTS PARTSUPP AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;

CREATE TABLE IF NOT EXISTS ORDERS AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

CREATE TABLE IF NOT EXISTS LINEITEM AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;
