-- Module 3: Data Loading
-- Create the database objects used throughout this module.
--
-- This module deliberately has its own database so its stages, file formats,
-- and loading experiments do not affect the earlier workshops. It owns only
-- the bronze layer: an auditable copy of data as it was delivered.

CREATE DATABASE IF NOT EXISTS DATA_LOADING;
CREATE SCHEMA IF NOT EXISTS DATA_LOADING.BRONZE;

USE DATABASE DATA_LOADING;
USE SCHEMA BRONZE;

-- File formats describe how Snowflake should interpret staged files.
CREATE OR REPLACE FILE FORMAT CSV_STANDARD_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE
  DATE_FORMAT = 'YYYY-MM-DD'
  TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE OR REPLACE FILE FORMAT CSV_NO_HEADER_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE;

-- events.json is an array of documents; device_readings.jsonl has one
-- document per line, so the two JSON formats intentionally differ.
CREATE OR REPLACE FILE FORMAT JSON_ARRAY_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE FILE FORMAT JSON_LINES_FORMAT
  TYPE = JSON;

CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT
  TYPE = PARQUET;

-- Named internal stages used by later loading exercises.
CREATE OR REPLACE STAGE BRONZE_CSV_STAGE
  FILE_FORMAT = CSV_STANDARD_FORMAT;

CREATE OR REPLACE STAGE BRONZE_JSON_STAGE
  FILE_FORMAT = JSON_ARRAY_FORMAT;

CREATE OR REPLACE STAGE BRONZE_JSON_LINES_STAGE
  FILE_FORMAT = JSON_LINES_FORMAT;

CREATE OR REPLACE STAGE BRONZE_PARQUET_STAGE
  FILE_FORMAT = PARQUET_FORMAT;

CREATE OR REPLACE STAGE BRONZE_REJECTED_FILES_STAGE;

-- The user stage (~) and table stages (for example @BRONZE_CUSTOMERS) are created
-- automatically by Snowflake. The named stages above are explicitly managed.

CREATE TABLE IF NOT EXISTS BRONZE_CUSTOMERS (
  CUSTOMER_ID NUMBER(10, 0),
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  EMAIL VARCHAR,
  PHONE VARCHAR,
  CITY VARCHAR,
  COUNTRY VARCHAR,
  SIGNUP_DATE DATE,
  MARKETING_OPT_IN BOOLEAN,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE_ORDERS (
  ORDER_ID NUMBER(12, 0),
  CUSTOMER_ID NUMBER(10, 0),
  ORDER_DATE DATE,
  STATUS VARCHAR,
  SALES_CHANNEL VARCHAR,
  CURRENCY VARCHAR(3),
  ORDER_TOTAL NUMBER(12, 2),
  DISCOUNT_AMOUNT NUMBER(12, 2),
  SHIPPING_CITY VARCHAR,
  SHIPPING_COUNTRY VARCHAR,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE_PRODUCT_CATALOG (
  PRODUCT_ID NUMBER(10, 0),
  SKU VARCHAR,
  PRODUCT_NAME VARCHAR,
  CATEGORY VARCHAR,
  BRAND VARCHAR,
  UNIT_PRICE NUMBER(10, 2),
  COST_PRICE NUMBER(10, 2),
  ACTIVE BOOLEAN,
  LAUNCH_DATE DATE,
  ATTRIBUTES VARIANT,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Bronze JSON tables preserve source documents before the transformations
-- module models them into silver relational structures.
CREATE TABLE IF NOT EXISTS BRONZE_WEB_EVENTS (
  EVENT VARIANT,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE_DEVICE_READINGS (
  READING VARIANT,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE_LOAD_AUDIT (
  LOAD_ID NUMBER AUTOINCREMENT,
  DATASET_NAME VARCHAR,
  SOURCE_FILE VARCHAR,
  ROWS_LOADED NUMBER,
  NOTES VARCHAR,
  RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
