-- Verify objects after dbt build, then inspect the same nodes in the Snowsight
-- dbt DAG. The physical names use dbt's default custom-schema generation.

USE ROLE DBT_DEVELOPER;
USE WAREHOUSE DBT_WH;
USE DATABASE DBT_ONBOARDING;

SHOW SCHEMAS LIKE 'DEV%' IN DATABASE DBT_ONBOARDING;

SHOW VIEWS IN SCHEMA DEV_STAGING;
SHOW VIEWS IN SCHEMA DEV_INTERMEDIATE;
SHOW TABLES IN SCHEMA DEV_MARTS;

SELECT *
FROM DEV_MARTS.CUSTOMER_ORDER_SUMMARY
ORDER BY CUSTOMER_ID, CURRENCY;

SELECT *
FROM DEV_MARTS.DAILY_SALES
ORDER BY ORDER_DATE, SHIPPING_COUNTRY, CURRENCY;

SELECT
  ORDER_ID,
  CUSTOMER_ID,
  STATUS,
  NET_ORDER_TOTAL,
  BRONZE_LOADED_AT,
  DBT_MODELED_AT
FROM DEV_MARTS.FCT_ORDERS
WHERE ORDER_ID IN (50015, 59999)
ORDER BY ORDER_ID;

SHOW DBT PROJECTS
  LIKE 'ONBOARDING_ANALYTICS'
  IN SCHEMA DBT_ONBOARDING.PROJECTS;
