SELECT
  CUSTOMERS.CUSTOMER_ID,
  CUSTOMERS.FIRST_NAME,
  CUSTOMERS.LAST_NAME,
  CUSTOMERS.COUNTRY,
  ORDERS.CURRENCY,
  COUNT(ORDERS.ORDER_ID) AS ORDER_COUNT,
  COALESCE(COUNT_IF(ORDERS.IS_COMPLETED), 0) AS COMPLETED_ORDER_COUNT,
  COALESCE(
    SUM(IFF(ORDERS.IS_COMPLETED, ORDERS.NET_ORDER_TOTAL, 0)),
    0
  ) AS NET_ORDER_TOTAL
FROM {{ ref('dim_customers') }} AS CUSTOMERS
LEFT JOIN {{ ref('fct_orders') }} AS ORDERS
  ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY
  CUSTOMERS.CUSTOMER_ID,
  CUSTOMERS.FIRST_NAME,
  CUSTOMERS.LAST_NAME,
  CUSTOMERS.COUNTRY,
  ORDERS.CURRENCY
