SELECT
  ORDER_DATE,
  SHIPPING_COUNTRY,
  CURRENCY,
  COUNT(*) AS ORDER_COUNT,
  SUM(ORDER_TOTAL) AS GROSS_ORDER_TOTAL,
  SUM(DISCOUNT_AMOUNT) AS DISCOUNT_AMOUNT,
  SUM(NET_ORDER_TOTAL) AS NET_ORDER_TOTAL
FROM {{ ref('fct_orders') }}
WHERE IS_COMPLETED
GROUP BY
  ORDER_DATE,
  SHIPPING_COUNTRY,
  CURRENCY
