SELECT
  CUSTOMER_ID,
  FIRST_NAME,
  LAST_NAME,
  EMAIL,
  PHONE,
  CITY,
  COUNTRY,
  SIGNUP_DATE,
  MARKETING_OPT_IN,
  BRONZE_LOADED_AT,
  CURRENT_TIMESTAMP() AS DBT_MODELED_AT
FROM {{ ref('int_customers_deduplicated') }}
