WITH SOURCE_CUSTOMERS AS (
  SELECT *
  FROM {{ source('load_transform_serve', 'bronze_customers') }}
),

NORMALIZED AS (
  SELECT
    CUSTOMER_ID,
    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    NULLIF(TRIM(PHONE), '') AS PHONE,
    INITCAP(TRIM(CITY)) AS CITY,
    TRIM(COUNTRY) AS COUNTRY,
    SIGNUP_DATE,
    MARKETING_OPT_IN,
    LOADED_AT AS BRONZE_LOADED_AT
  FROM SOURCE_CUSTOMERS
)

SELECT *
FROM NORMALIZED
