WITH SOURCE_ORDERS AS (
  SELECT *
  FROM {{ source('load_transform_serve', 'bronze_orders') }}
),

NORMALIZED AS (
  SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    UPPER(TRIM(STATUS)) AS STATUS,
    UPPER(TRIM(SALES_CHANNEL)) AS SALES_CHANNEL,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    ORDER_TOTAL,
    DISCOUNT_AMOUNT,
    INITCAP(TRIM(SHIPPING_CITY)) AS SHIPPING_CITY,
    TRIM(SHIPPING_COUNTRY) AS SHIPPING_COUNTRY,
    LOADED_AT AS BRONZE_LOADED_AT
  FROM SOURCE_ORDERS
)

SELECT *
FROM NORMALIZED
