-- Chapter 5: Security
-- Grant least-privilege access to current and future workshop objects.

USE ROLE SECURITYADMIN;

-- All functional roles need compute and database usage before any object-level
-- SELECT or DML privilege can be exercised.
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE FINANCE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HR;

GRANT USAGE ON DATABASE LOAD_TRANSFORM_SERVE TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE LOAD_TRANSFORM_SERVE TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE LOAD_TRANSFORM_SERVE TO ROLE FINANCE;
GRANT USAGE ON DATABASE LOAD_TRANSFORM_SERVE TO ROLE HR;

-- DATA_ENGINEER operates the complete medallion pipeline.
GRANT USAGE ON SCHEMA LOAD_TRANSFORM_SERVE.BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.BRONZE
  TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.BRONZE
  TO ROLE DATA_ENGINEER;

GRANT READ, WRITE
  ON ALL STAGES IN SCHEMA LOAD_TRANSFORM_SERVE.BRONZE
  TO ROLE DATA_ENGINEER;
GRANT READ, WRITE
  ON FUTURE STAGES IN SCHEMA LOAD_TRANSFORM_SERVE.BRONZE
  TO ROLE DATA_ENGINEER;

GRANT SELECT
  ON ALL STREAMS IN SCHEMA LOAD_TRANSFORM_SERVE.BRONZE
  TO ROLE DATA_ENGINEER;
GRANT SELECT
  ON FUTURE STREAMS IN SCHEMA LOAD_TRANSFORM_SERVE.BRONZE
  TO ROLE DATA_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW,
      CREATE DYNAMIC TABLE, CREATE STREAM, CREATE TASK
  ON SCHEMA LOAD_TRANSFORM_SERVE.SILVER
  TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW,
      CREATE DYNAMIC TABLE, CREATE STREAM, CREATE TASK
  ON SCHEMA LOAD_TRANSFORM_SERVE.GOLD
  TO ROLE DATA_ENGINEER;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DATA_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER
  TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER
  TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD
  TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD
  TO ROLE DATA_ENGINEER;

GRANT SELECT ON ALL VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ENGINEER;
GRANT SELECT, MONITOR ON ALL DYNAMIC TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ENGINEER;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ENGINEER;
GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ENGINEER;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ENGINEER;

-- DATA_ANALYST reads curated silver and gold objects, including new objects
-- created after this script via future grants. Bronze is intentionally absent.
-- It also receives explicit, policy-controlled access to the compensation
-- table for an approved workforce-analysis use case.
GRANT USAGE ON SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA LOAD_TRANSFORM_SERVE.SENSITIVE TO ROLE DATA_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA LOAD_TRANSFORM_SERVE.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON TABLE LOAD_TRANSFORM_SERVE.SENSITIVE.EMPLOYEE_COMPENSATION
  TO ROLE DATA_ANALYST;

-- FINANCE receives only the protected compensation table. Its row policy
-- reduces the result to Finance employees; email remains masked.
GRANT USAGE ON SCHEMA LOAD_TRANSFORM_SERVE.SENSITIVE TO ROLE FINANCE;
GRANT SELECT ON TABLE LOAD_TRANSFORM_SERVE.SENSITIVE.EMPLOYEE_COMPENSATION
  TO ROLE FINANCE;

-- HR receives only the protected employee table. The policies allow HR to see
-- every department, exact salary, and unmasked tagged email addresses.
GRANT USAGE ON SCHEMA LOAD_TRANSFORM_SERVE.SENSITIVE TO ROLE HR;
GRANT SELECT ON TABLE LOAD_TRANSFORM_SERVE.SENSITIVE.EMPLOYEE_COMPENSATION
  TO ROLE HR;

SHOW FUTURE GRANTS TO ROLE DATA_ENGINEER;
SHOW FUTURE GRANTS TO ROLE DATA_ANALYST;
SHOW FUTURE GRANTS TO ROLE FINANCE;
