-- Module 3: Data Loading
-- Review load metadata for the COPY INTO and Snowpipe exercises.
-- COPY_HISTORY covers the last 14 days and includes both bulk COPY and
-- Snowpipe activity.

USE DATABASE LOAD_TRANSFORM_SERVE;
USE SCHEMA BRONZE;

SELECT
  FILE_NAME,
  STAGE_LOCATION,
  LAST_LOAD_TIME,
  STATUS,
  ROW_COUNT,
  ROW_PARSED,
  ERROR_COUNT,
  FIRST_ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'LOAD_TRANSFORM_SERVE.BRONZE.BRONZE_ORDERS',
  START_TIME => DATEADD('day', -14, CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC;

-- Repeat the same metadata view for the Parquet and JSON COPY loads.
SELECT
  FILE_NAME, STAGE_LOCATION, LAST_LOAD_TIME, STATUS,
  ROW_COUNT, ROW_PARSED, ERROR_COUNT, FIRST_ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'LOAD_TRANSFORM_SERVE.BRONZE.BRONZE_PRODUCT_CATALOG',
  START_TIME => DATEADD('day', -14, CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC;

SELECT
  FILE_NAME, STAGE_LOCATION, LAST_LOAD_TIME, STATUS,
  ROW_COUNT, ROW_PARSED, ERROR_COUNT, FIRST_ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'LOAD_TRANSFORM_SERVE.BRONZE.BRONZE_WEB_EVENTS',
  START_TIME => DATEADD('day', -14, CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC;

-- Filter COPY_HISTORY by pipe name to isolate the Snowpipe load.
SELECT
  FILE_NAME, STAGE_LOCATION, LAST_LOAD_TIME, STATUS,
  ROW_COUNT, ROW_PARSED, ERROR_COUNT, FIRST_ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'LOAD_TRANSFORM_SERVE.BRONZE.BRONZE_DEVICE_READINGS',
  START_TIME => DATEADD('day', -14, CURRENT_TIMESTAMP()),
  PIPE_NAME => 'LOAD_TRANSFORM_SERVE.BRONZE.BRONZE_DEVICE_READINGS_PIPE'
))
ORDER BY LAST_LOAD_TIME DESC;

-- Account Usage retains COPY_HISTORY for longer, but can have latency and may
-- require a role with access to the SNOWFLAKE database.
SELECT
  FILE_NAME,
  TABLE_NAME,
  LAST_LOAD_TIME,
  STATUS,
  ROW_COUNT,
  ERROR_COUNT,
  FIRST_ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
WHERE TABLE_CATALOG_NAME = 'LOAD_TRANSFORM_SERVE'
  AND TABLE_SCHEMA_NAME = 'BRONZE'
  AND TABLE_NAME IN (
    'BRONZE_CUSTOMERS',
    'BRONZE_ORDERS',
    'BRONZE_PRODUCT_CATALOG',
    'BRONZE_WEB_EVENTS',
    'BRONZE_DEVICE_READINGS'
  )
ORDER BY LAST_LOAD_TIME DESC;
