-- Module 4: Transformation and Serving
-- Build silver tables with common full-refresh transformation patterns.
-- Run 01_setup_silver_gold.sql after completing the data-loading module.

USE DATABASE LOAD_TRANSFORM_SERVE;

-- CTAS (CREATE TABLE AS SELECT) creates and populates a clean customer table
-- in one statement. QUALIFY keeps the most recently loaded version per ID.
CREATE OR REPLACE TABLE SILVER.SILVER_CUSTOMERS AS
SELECT
  CUSTOMER_ID,
  INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
  INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
  LOWER(TRIM(EMAIL)) AS EMAIL,
  PHONE,
  INITCAP(TRIM(CITY)) AS CITY,
  COUNTRY,
  SIGNUP_DATE,
  MARKETING_OPT_IN,
  LOADED_AT AS BRONZE_LOADED_AT,
  CURRENT_TIMESTAMP() AS TRANSFORMED_AT
FROM BRONZE.BRONZE_CUSTOMERS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY CUSTOMER_ID
  ORDER BY LOADED_AT DESC
) = 1;

-- INSERT INTO ... SELECT loads a pre-defined table. The explicit table
-- definition makes this pattern useful when types and column contracts must
-- be controlled separately from the transformation query.
CREATE TABLE IF NOT EXISTS SILVER.SILVER_ORDERS (
  ORDER_ID NUMBER(12, 0),
  CUSTOMER_ID NUMBER(10, 0),
  ORDER_DATE DATE,
  STATUS VARCHAR,
  SALES_CHANNEL VARCHAR,
  CURRENCY VARCHAR(3),
  ORDER_TOTAL NUMBER(12, 2),
  DISCOUNT_AMOUNT NUMBER(12, 2),
  NET_ORDER_TOTAL NUMBER(12, 2),
  SHIPPING_CITY VARCHAR,
  SHIPPING_COUNTRY VARCHAR,
  IS_COMPLETED BOOLEAN,
  BRONZE_LOADED_AT TIMESTAMP_LTZ,
  TRANSFORMED_AT TIMESTAMP_LTZ
);

INSERT INTO SILVER.SILVER_ORDERS (
  ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, SALES_CHANNEL,
  CURRENCY, ORDER_TOTAL, DISCOUNT_AMOUNT, NET_ORDER_TOTAL,
  SHIPPING_CITY, SHIPPING_COUNTRY, IS_COMPLETED,
  BRONZE_LOADED_AT, TRANSFORMED_AT
)
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_DATE,
  UPPER(TRIM(STATUS)),
  UPPER(TRIM(SALES_CHANNEL)),
  CURRENCY,
  ORDER_TOTAL,
  DISCOUNT_AMOUNT,
  ORDER_TOTAL - DISCOUNT_AMOUNT,
  INITCAP(TRIM(SHIPPING_CITY)),
  SHIPPING_COUNTRY,
  STATUS IN ('DELIVERED', 'SHIPPED'),
  LOADED_AT,
  CURRENT_TIMESTAMP()
FROM BRONZE.BRONZE_ORDERS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY ORDER_ID
  ORDER BY LOADED_AT DESC
) = 1;

-- TRUNCATE + INSERT implements an explicit full refresh while retaining the
-- target table's grants and definition. Re-run this block to refresh orders.
TRUNCATE TABLE SILVER.SILVER_ORDERS;

INSERT INTO SILVER.SILVER_ORDERS (
  ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, SALES_CHANNEL,
  CURRENCY, ORDER_TOTAL, DISCOUNT_AMOUNT, NET_ORDER_TOTAL,
  SHIPPING_CITY, SHIPPING_COUNTRY, IS_COMPLETED,
  BRONZE_LOADED_AT, TRANSFORMED_AT
)
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_DATE,
  UPPER(TRIM(STATUS)),
  UPPER(TRIM(SALES_CHANNEL)),
  CURRENCY,
  ORDER_TOTAL,
  DISCOUNT_AMOUNT,
  ORDER_TOTAL - DISCOUNT_AMOUNT,
  INITCAP(TRIM(SHIPPING_CITY)),
  SHIPPING_COUNTRY,
  STATUS IN ('DELIVERED', 'SHIPPED'),
  LOADED_AT,
  CURRENT_TIMESTAMP()
FROM BRONZE.BRONZE_ORDERS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY ORDER_ID
  ORDER BY LOADED_AT DESC
) = 1;

-- CREATE OR REPLACE TABLE AS SELECT replaces both the product-table contents
-- and its definition. Use it only when replacing the object is acceptable.
CREATE OR REPLACE TABLE SILVER.SILVER_PRODUCTS AS
SELECT
  PRODUCT_ID,
  SKU,
  PRODUCT_NAME,
  CATEGORY,
  BRAND,
  UNIT_PRICE,
  COST_PRICE,
  UNIT_PRICE - COST_PRICE AS UNIT_MARGIN,
  ACTIVE,
  LAUNCH_DATE,
  ATTRIBUTES,
  SOURCE_FILE,
  LOADED_AT AS BRONZE_LOADED_AT,
  CURRENT_TIMESTAMP() AS TRANSFORMED_AT
FROM BRONZE.BRONZE_PRODUCT_CATALOG
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY PRODUCT_ID
  ORDER BY LOADED_AT DESC
) = 1;

-- A second CTAS turns the raw JSON documents into a typed silver event table.
CREATE OR REPLACE TABLE SILVER.SILVER_WEB_EVENTS AS
SELECT
  EVENT:event_id::VARCHAR AS EVENT_ID,
  EVENT:event_type::VARCHAR AS EVENT_TYPE,
  TRY_TO_TIMESTAMP_TZ(EVENT:occurred_at::VARCHAR) AS OCCURRED_AT,
  EVENT:customer_id::NUMBER(10, 0) AS CUSTOMER_ID,
  EVENT:session_id::VARCHAR AS SESSION_ID,
  EVENT:page:path::VARCHAR AS PAGE_PATH,
  EVENT:product:product_id::NUMBER(10, 0) AS PRODUCT_ID,
  EVENT:product:quantity::NUMBER(10, 0) AS PRODUCT_QUANTITY,
  EVENT:device:type::VARCHAR AS DEVICE_TYPE,
  EVENT:utm:source::VARCHAR AS UTM_SOURCE,
  EVENT AS RAW_EVENT,
  SOURCE_FILE,
  LOADED_AT AS BRONZE_LOADED_AT,
  CURRENT_TIMESTAMP() AS TRANSFORMED_AT
FROM BRONZE.BRONZE_WEB_EVENTS;

SELECT 'SILVER_CUSTOMERS' AS table_name, COUNT(*) AS row_count FROM SILVER.SILVER_CUSTOMERS
UNION ALL
SELECT 'SILVER_ORDERS', COUNT(*) FROM SILVER.SILVER_ORDERS
UNION ALL
SELECT 'SILVER_PRODUCTS', COUNT(*) FROM SILVER.SILVER_PRODUCTS
UNION ALL
SELECT 'SILVER_WEB_EVENTS', COUNT(*) FROM SILVER.SILVER_WEB_EVENTS
ORDER BY table_name;
