-- Module 4: Transformation and Serving
-- Process new bronze orders incrementally with a stream and task, then use a
-- dynamic table to maintain a gold aggregate.
-- Run 02_full_refresh_transformation_patterns.sql first.

USE DATABASE LOAD_TRANSFORM_SERVE;

-- An append-only stream tracks orders inserted after the stream is created.
-- It is appropriate for an ingestion feed that does not send source deletes.
CREATE OR REPLACE STREAM BRONZE.BRONZE_ORDERS_STREAM
  ON TABLE BRONZE.BRONZE_ORDERS
  APPEND_ONLY = TRUE;

-- MERGE is the incremental upsert pattern: matching order IDs are updated and
-- new order IDs are inserted. The stream is consumed only when this statement
-- executes successfully.
MERGE INTO SILVER.SILVER_ORDERS AS TARGET
USING (
  SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    UPPER(TRIM(STATUS)) AS STATUS,
    UPPER(TRIM(SALES_CHANNEL)) AS SALES_CHANNEL,
    CURRENCY,
    ORDER_TOTAL,
    DISCOUNT_AMOUNT,
    ORDER_TOTAL - DISCOUNT_AMOUNT AS NET_ORDER_TOTAL,
    INITCAP(TRIM(SHIPPING_CITY)) AS SHIPPING_CITY,
    SHIPPING_COUNTRY,
    STATUS IN ('DELIVERED', 'SHIPPED') AS IS_COMPLETED,
    LOADED_AT AS BRONZE_LOADED_AT,
    CURRENT_TIMESTAMP() AS TRANSFORMED_AT
  FROM BRONZE.BRONZE_ORDERS_STREAM
) AS SOURCE
ON TARGET.ORDER_ID = SOURCE.ORDER_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = SOURCE.CUSTOMER_ID,
  ORDER_DATE = SOURCE.ORDER_DATE,
  STATUS = SOURCE.STATUS,
  SALES_CHANNEL = SOURCE.SALES_CHANNEL,
  CURRENCY = SOURCE.CURRENCY,
  ORDER_TOTAL = SOURCE.ORDER_TOTAL,
  DISCOUNT_AMOUNT = SOURCE.DISCOUNT_AMOUNT,
  NET_ORDER_TOTAL = SOURCE.NET_ORDER_TOTAL,
  SHIPPING_CITY = SOURCE.SHIPPING_CITY,
  SHIPPING_COUNTRY = SOURCE.SHIPPING_COUNTRY,
  IS_COMPLETED = SOURCE.IS_COMPLETED,
  BRONZE_LOADED_AT = SOURCE.BRONZE_LOADED_AT,
  TRANSFORMED_AT = SOURCE.TRANSFORMED_AT
WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, SALES_CHANNEL,
  CURRENCY, ORDER_TOTAL, DISCOUNT_AMOUNT, NET_ORDER_TOTAL,
  SHIPPING_CITY, SHIPPING_COUNTRY, IS_COMPLETED,
  BRONZE_LOADED_AT, TRANSFORMED_AT
) VALUES (
  SOURCE.ORDER_ID, SOURCE.CUSTOMER_ID, SOURCE.ORDER_DATE, SOURCE.STATUS,
  SOURCE.SALES_CHANNEL, SOURCE.CURRENCY, SOURCE.ORDER_TOTAL,
  SOURCE.DISCOUNT_AMOUNT, SOURCE.NET_ORDER_TOTAL, SOURCE.SHIPPING_CITY,
  SOURCE.SHIPPING_COUNTRY, SOURCE.IS_COMPLETED, SOURCE.BRONZE_LOADED_AT,
  SOURCE.TRANSFORMED_AT
);

-- The task automates the same MERGE for future stream changes.
CREATE OR REPLACE TASK SILVER.SILVER_ORDERS_INCREMENTAL_TASK
  WAREHOUSE = TUTO_WH
  SCHEDULE = '5 MINUTES'
  WHEN SYSTEM$STREAM_HAS_DATA('LOAD_TRANSFORM_SERVE.BRONZE.BRONZE_ORDERS_STREAM')
AS
MERGE INTO SILVER.SILVER_ORDERS AS TARGET
USING (
  SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    UPPER(TRIM(STATUS)) AS STATUS,
    UPPER(TRIM(SALES_CHANNEL)) AS SALES_CHANNEL,
    CURRENCY,
    ORDER_TOTAL,
    DISCOUNT_AMOUNT,
    ORDER_TOTAL - DISCOUNT_AMOUNT AS NET_ORDER_TOTAL,
    INITCAP(TRIM(SHIPPING_CITY)) AS SHIPPING_CITY,
    SHIPPING_COUNTRY,
    STATUS IN ('DELIVERED', 'SHIPPED') AS IS_COMPLETED,
    LOADED_AT AS BRONZE_LOADED_AT,
    CURRENT_TIMESTAMP() AS TRANSFORMED_AT
  FROM BRONZE.BRONZE_ORDERS_STREAM
) AS SOURCE
ON TARGET.ORDER_ID = SOURCE.ORDER_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = SOURCE.CUSTOMER_ID,
  ORDER_DATE = SOURCE.ORDER_DATE,
  STATUS = SOURCE.STATUS,
  SALES_CHANNEL = SOURCE.SALES_CHANNEL,
  CURRENCY = SOURCE.CURRENCY,
  ORDER_TOTAL = SOURCE.ORDER_TOTAL,
  DISCOUNT_AMOUNT = SOURCE.DISCOUNT_AMOUNT,
  NET_ORDER_TOTAL = SOURCE.NET_ORDER_TOTAL,
  SHIPPING_CITY = SOURCE.SHIPPING_CITY,
  SHIPPING_COUNTRY = SOURCE.SHIPPING_COUNTRY,
  IS_COMPLETED = SOURCE.IS_COMPLETED,
  BRONZE_LOADED_AT = SOURCE.BRONZE_LOADED_AT,
  TRANSFORMED_AT = SOURCE.TRANSFORMED_AT
WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, SALES_CHANNEL,
  CURRENCY, ORDER_TOTAL, DISCOUNT_AMOUNT, NET_ORDER_TOTAL,
  SHIPPING_CITY, SHIPPING_COUNTRY, IS_COMPLETED,
  BRONZE_LOADED_AT, TRANSFORMED_AT
) VALUES (
  SOURCE.ORDER_ID, SOURCE.CUSTOMER_ID, SOURCE.ORDER_DATE, SOURCE.STATUS,
  SOURCE.SALES_CHANNEL, SOURCE.CURRENCY, SOURCE.ORDER_TOTAL,
  SOURCE.DISCOUNT_AMOUNT, SOURCE.NET_ORDER_TOTAL, SOURCE.SHIPPING_CITY,
  SOURCE.SHIPPING_COUNTRY, SOURCE.IS_COMPLETED, SOURCE.BRONZE_LOADED_AT,
  SOURCE.TRANSFORMED_AT
);

-- New tasks are suspended by default. Resume only when you are ready to let
-- Snowflake check the stream every five minutes; suspend it again afterwards.
-- ALTER TASK SILVER.SILVER_ORDERS_INCREMENTAL_TASK RESUME;
-- ALTER TASK SILVER.SILVER_ORDERS_INCREMENTAL_TASK SUSPEND;

SHOW STREAMS IN SCHEMA BRONZE;
SHOW TASKS IN SCHEMA SILVER;

-- Dynamic tables declare the result and a freshness target. Snowflake manages
-- the refresh work instead of requiring a stream/task implementation.
CREATE OR REPLACE DYNAMIC TABLE GOLD.DT_DAILY_SALES (
  ORDER_DATE,
  SHIPPING_COUNTRY,
  CURRENCY,
  ORDER_COUNT,
  GROSS_ORDER_TOTAL,
  NET_ORDER_TOTAL
)
  TARGET_LAG = '5 MINUTES'
  WAREHOUSE = COMPUTE_WH
  REFRESH_MODE = INCREMENTAL
AS
SELECT
  ORDER_DATE,
  SHIPPING_COUNTRY,
  CURRENCY,
  COUNT(*) AS ORDER_COUNT,
  SUM(ORDER_TOTAL) AS GROSS_ORDER_TOTAL,
  SUM(NET_ORDER_TOTAL) AS NET_ORDER_TOTAL
FROM SILVER.SILVER_ORDERS
WHERE IS_COMPLETED
GROUP BY ORDER_DATE, SHIPPING_COUNTRY, CURRENCY;

SHOW DYNAMIC TABLES IN SCHEMA GOLD;
SELECT * FROM GOLD.DT_DAILY_SALES ORDER BY ORDER_DATE, SHIPPING_COUNTRY, CURRENCY;
