-- Chapter 6: Management
-- Attribute spend through governed warehouse and user tags, inspect actual
-- metering, and compare theoretical warehouse costs.

USE ROLE MANAGEMENT_ADMIN;
USE WAREHOUSE MGMT_XS_WH;

-- Actual metering includes warehouse runtime, including idle time. ACCOUNT_USAGE
-- can lag, so a newly used warehouse might not appear immediately.
SELECT
  WAREHOUSE_NAME,
  ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS,
  ROUND(SUM(CREDITS_USED_COMPUTE), 4) AS COMPUTE_CREDITS,
  ROUND(SUM(CREDITS_USED_CLOUD_SERVICES), 4) AS CLOUD_SERVICES_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME LIKE 'MGMT%WH'
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_CREDITS DESC;

-- Pivot the governed warehouse classifications, then join metering by stable
-- object ID rather than display name. TAG_REFERENCES can take up to two hours
-- to reflect a new association.
WITH WAREHOUSE_CLASSIFICATION AS (
  SELECT
    OBJECT_ID AS WAREHOUSE_ID,
    MAX(IFF(TAG_NAME = 'COST_CENTER', TAG_VALUE, NULL)) AS COST_CENTER,
    MAX(IFF(TAG_NAME = 'WORKLOAD_TYPE', TAG_VALUE, NULL)) AS WORKLOAD_TYPE,
    MAX(IFF(TAG_NAME = 'ENVIRONMENT', TAG_VALUE, NULL)) AS ENVIRONMENT
  FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
  WHERE TAG_DATABASE = 'MANAGEMENT_LAB'
    AND TAG_SCHEMA = 'GOVERNANCE'
    AND TAG_NAME IN ('COST_CENTER', 'WORKLOAD_TYPE', 'ENVIRONMENT')
    AND DOMAIN = 'WAREHOUSE'
    AND OBJECT_DELETED IS NULL
  GROUP BY OBJECT_ID
)
SELECT
  C.COST_CENTER,
  C.WORKLOAD_TYPE,
  C.ENVIRONMENT,
  ROUND(SUM(M.CREDITS_USED), 4) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY M
JOIN WAREHOUSE_CLASSIFICATION C
  ON M.WAREHOUSE_ID = C.WAREHOUSE_ID
WHERE M.START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
GROUP BY C.COST_CENTER, C.WORKLOAD_TYPE, C.ENVIRONMENT
ORDER BY TOTAL_CREDITS DESC;

-- For shared warehouses, Snowflake recommends attributing human query costs by
-- joining QUERY_ATTRIBUTION_HISTORY to governed tags on USER objects. The role
-- comes from QUERY_HISTORY; none of these dimensions requires user-entered
-- QUERY_TAG text. Per-query attribution excludes idle time and can lag.
WITH USER_COST_CENTERS AS (
  SELECT
    OBJECT_NAME AS USER_NAME,
    TAG_VALUE AS COST_CENTER
  FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
  WHERE TAG_DATABASE = 'MANAGEMENT_LAB'
    AND TAG_SCHEMA = 'GOVERNANCE'
    AND TAG_NAME = 'COST_CENTER'
    AND DOMAIN = 'USER'
    AND OBJECT_DELETED IS NULL
),
ATTRIBUTED_QUERIES AS (
  SELECT
    QUERY_ID,
    USER_NAME,
    WAREHOUSE_NAME,
    CREDITS_ATTRIBUTED_COMPUTE,
    CREDITS_USED_QUERY_ACCELERATION
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
  WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME LIKE 'MGMT%WH'
),
QUERY_ROLES AS (
  SELECT QUERY_ID, ROLE_NAME
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
  WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME LIKE 'MGMT%WH'
)
SELECT
  COALESCE(U.COST_CENTER, 'UNCLASSIFIED') AS COST_CENTER,
  Q.USER_NAME,
  COALESCE(R.ROLE_NAME, 'UNKNOWN') AS ROLE_NAME,
  Q.WAREHOUSE_NAME,
  ROUND(SUM(Q.CREDITS_ATTRIBUTED_COMPUTE), 6)
    AS ATTRIBUTED_COMPUTE_CREDITS,
  ROUND(SUM(COALESCE(Q.CREDITS_USED_QUERY_ACCELERATION, 0)), 6)
    AS QUERY_ACCELERATION_CREDITS
FROM ATTRIBUTED_QUERIES Q
LEFT JOIN USER_COST_CENTERS U
  ON Q.USER_NAME = U.USER_NAME
LEFT JOIN QUERY_ROLES R
  ON Q.QUERY_ID = R.QUERY_ID
GROUP BY
  COALESCE(U.COST_CENTER, 'UNCLASSIFIED'),
  Q.USER_NAME,
  COALESCE(R.ROLE_NAME, 'UNKNOWN'),
  Q.WAREHOUSE_NAME
ORDER BY ATTRIBUTED_COMPUTE_CREDITS DESC;

-- Theoretical Gen1 Standard warehouse comparison. Snowflake bills per second
-- with a 60-second minimum each time a warehouse starts. Dollar cost depends on
-- the organization's contract, so the price below is deliberately an input.
SET ASSUMED_PRICE_PER_CREDIT_USD = 3.00;

WITH WAREHOUSE_RATES AS (
  SELECT COLUMN1 AS WAREHOUSE_SIZE, COLUMN2 AS CREDITS_PER_HOUR
  FROM VALUES
    ('X-SMALL', 1),
    ('SMALL', 2),
    ('MEDIUM', 4)
),
RUNTIME_SCENARIOS AS (
  SELECT COLUMN1 AS SCENARIO, COLUMN2 AS RUNTIME_SECONDS
  FROM VALUES
    ('30-second query after resume', 30),
    ('10-minute continuous workload', 600),
    ('1-hour continuous workload', 3600)
)
SELECT
  R.SCENARIO,
  W.WAREHOUSE_SIZE,
  W.CREDITS_PER_HOUR,
  GREATEST(R.RUNTIME_SECONDS, 60) AS BILLABLE_SECONDS,
  ROUND(
    W.CREDITS_PER_HOUR * GREATEST(R.RUNTIME_SECONDS, 60) / 3600,
    4
  ) AS ESTIMATED_CREDITS,
  ROUND(
    W.CREDITS_PER_HOUR * GREATEST(R.RUNTIME_SECONDS, 60) / 3600
      * $ASSUMED_PRICE_PER_CREDIT_USD,
    2
  ) AS ILLUSTRATIVE_COST_USD
FROM WAREHOUSE_RATES W
CROSS JOIN RUNTIME_SCENARIOS R
ORDER BY R.RUNTIME_SECONDS, W.CREDITS_PER_HOUR;
