-- Chapter 6: Management
-- Recover from accidental DML and DROP operations with Time Travel.
-- The exercise uses an isolated copy; source workshop tables are untouched.

USE ROLE MANAGEMENT_ADMIN;
USE WAREHOUSE MGMT_XS_WH;
USE DATABASE MANAGEMENT_LAB;
USE SCHEMA RECOVERY;

CREATE OR REPLACE TABLE ORDERS_RECOVERY_LAB
  DATA_RETENTION_TIME_IN_DAYS = 1
AS
SELECT
  SEQ4() + 1 AS ORDER_ID,
  DATEADD('DAY', -MOD(SEQ4(), 30), CURRENT_DATE()) AS ORDER_DATE,
  ROUND(10 + UNIFORM(0::FLOAT, 990::FLOAT, RANDOM()), 2) AS ORDER_TOTAL
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

SELECT COUNT(*) AS ORIGINAL_ROW_COUNT FROM ORDERS_RECOVERY_LAB;

-- Simulate accidental DML and capture its query ID. BEFORE(STATEMENT) returns
-- the table state immediately before that statement completed.
DELETE FROM ORDERS_RECOVERY_LAB
WHERE ORDER_DATE = (SELECT MIN(ORDER_DATE) FROM ORDERS_RECOVERY_LAB);

SET destructive_query_id = LAST_QUERY_ID();

SELECT COUNT(*) AS ROW_COUNT_AFTER_DELETE FROM ORDERS_RECOVERY_LAB;

SELECT COUNT(*) AS ROW_COUNT_BEFORE_DELETE
FROM ORDERS_RECOVERY_LAB
BEFORE(STATEMENT => $destructive_query_id);

-- Create a zero-copy recovery snapshot at the known-good point in history.
CREATE OR REPLACE TABLE ORDERS_BEFORE_DELETE
  CLONE ORDERS_RECOVERY_LAB
  BEFORE(STATEMENT => $destructive_query_id);

TRUNCATE TABLE ORDERS_RECOVERY_LAB;

INSERT INTO ORDERS_RECOVERY_LAB
SELECT * FROM ORDERS_BEFORE_DELETE;

SELECT COUNT(*) AS RESTORED_ROW_COUNT FROM ORDERS_RECOVERY_LAB;

-- UNDROP restores the most recently dropped object with this name while it is
-- still inside its retention period.
DROP TABLE ORDERS_RECOVERY_LAB;

SHOW TABLES HISTORY LIKE 'ORDERS_RECOVERY_LAB' IN SCHEMA MANAGEMENT_LAB.RECOVERY;

UNDROP TABLE ORDERS_RECOVERY_LAB;

SELECT COUNT(*) AS ROW_COUNT_AFTER_UNDROP FROM ORDERS_RECOVERY_LAB;
