-- Chapter 6: Management
-- Optional cleanup. Review each statement before uncommenting it.

-- USE ROLE MANAGEMENT_ADMIN;
-- DROP SNOWFLAKE.CORE.BUDGET IF EXISTS
--   MANAGEMENT_LAB.GOVERNANCE.MANAGEMENT_DATA_PLATFORM_BUDGET;

-- USE ROLE ACCOUNTADMIN;
-- DROP RESOURCE MONITOR IF EXISTS MANAGEMENT_LAB_MONITOR;

-- USE ROLE GOVERNANCE_ADMIN;
-- DROP TAG IF EXISTS MANAGEMENT_LAB.GOVERNANCE.ENVIRONMENT;
-- DROP TAG IF EXISTS MANAGEMENT_LAB.GOVERNANCE.WORKLOAD_TYPE;
-- DROP TAG IF EXISTS MANAGEMENT_LAB.GOVERNANCE.COST_CENTER;

-- USE ROLE SYSADMIN;
-- DROP WAREHOUSE IF EXISTS MGMT_XS_WH;
-- DROP WAREHOUSE IF EXISTS MGMT_SMALL_WH;
-- DROP WAREHOUSE IF EXISTS MGMT_MEDIUM_WH;
-- DROP DATABASE IF EXISTS LOAD_TRANSFORM_SERVE_DEV;
-- DROP DATABASE IF EXISTS MANAGEMENT_LAB;

-- USE ROLE SECURITYADMIN;
-- DROP ROLE IF EXISTS MANAGEMENT_ADMIN;
