-- Chapter 2: Semi-structured data workshop
-- Create the objects used to stage and load the JSON sample files.

CREATE DATABASE IF NOT EXISTS SQL_IN_SNOWFLAKE;
CREATE SCHEMA IF NOT EXISTS SQL_IN_SNOWFLAKE.SEMI_STRUCTURED;

USE DATABASE SQL_IN_SNOWFLAKE;
USE SCHEMA SEMI_STRUCTURED;

-- The sample files are JSON arrays. Strip the outer [ ] so each object loads
-- as one row in a VARIANT column.
CREATE OR REPLACE FILE FORMAT JSON_ARRAY_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE STAGE JSON_WORKSHOP_STAGE
  FILE_FORMAT = JSON_ARRAY_FORMAT;

-- Keep the original JSON document in VARIANT. Source-file and load-time
-- metadata make the raw layer easier to audit.
CREATE TABLE IF NOT EXISTS RAW_ORDERS (
  SRC VARIANT,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_CUSTOMERS (
  SRC VARIANT,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_EVENTS (
  SRC VARIANT,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
