-- Chapter 7: Performance
-- Provision an isolated role, database, and warehouse for repeatable tests.

USE ROLE SECURITYADMIN;

CREATE ROLE PERFORMANCE_ENGINEER
  COMMENT = 'Runs controlled query-performance experiments';

GRANT ROLE PERFORMANCE_ENGINEER TO ROLE SYSADMIN;

SET workshop_user = CURRENT_USER();
GRANT ROLE PERFORMANCE_ENGINEER TO USER IDENTIFIER($workshop_user);

-- Imported privileges are granted at the shared-database level. The sample
-- database is read-only, so the workshop cannot alter its tables.
USE ROLE ACCOUNTADMIN;

-- Newer accounts normally include this database. If it is absent, create it
-- once before continuing:
-- CREATE DATABASE SNOWFLAKE_SAMPLE_DATA
--   FROM SHARE SFC_SAMPLES.SAMPLE_DATA;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA
  TO ROLE PERFORMANCE_ENGINEER;

USE ROLE SYSADMIN;

CREATE DATABASE PERFORMANCE_LAB
  COMMENT = 'Isolated objects and measurements for the performance workshop';

GRANT USAGE, CREATE SCHEMA ON DATABASE PERFORMANCE_LAB
  TO ROLE PERFORMANCE_ENGINEER;

CREATE WAREHOUSE PERF_TEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 900
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
  COMMENT = 'Single-cluster warehouse for controlled performance comparisons';

GRANT USAGE, MONITOR, OPERATE, MODIFY
  ON WAREHOUSE PERF_TEST_WH TO ROLE PERFORMANCE_ENGINEER;

-- Reuse the governed cost taxonomy established in Chapter 6.
USE ROLE GOVERNANCE_ADMIN;

ALTER DATABASE PERFORMANCE_LAB SET TAG
  MANAGEMENT_LAB.GOVERNANCE.COST_CENTER = 'DATA_PLATFORM',
  MANAGEMENT_LAB.GOVERNANCE.ENVIRONMENT = 'TRAINING';

ALTER WAREHOUSE PERF_TEST_WH SET TAG
  MANAGEMENT_LAB.GOVERNANCE.COST_CENTER = 'DATA_PLATFORM',
  MANAGEMENT_LAB.GOVERNANCE.WORKLOAD_TYPE = 'BI',
  MANAGEMENT_LAB.GOVERNANCE.ENVIRONMENT = 'TRAINING';

USE ROLE PERFORMANCE_ENGINEER;
USE DATABASE PERFORMANCE_LAB;
USE WAREHOUSE PERF_TEST_WH;

CREATE SCHEMA BENCHMARKS
  COMMENT = 'Benchmark metadata and local optimization candidates';

CREATE TRANSIENT TABLE BENCHMARKS.RUN_LOG (
  EXPERIMENT VARCHAR NOT NULL,
  RUN_LABEL VARCHAR NOT NULL,
  QUERY_ID VARCHAR NOT NULL,
  NOTES VARCHAR,
  CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = 0
COMMENT = 'Query IDs captured for immediate comparison through Query History';

-- Confirm that the expected large sample table is available before continuing.
SHOW TABLES LIKE 'LINEITEM'
  IN SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF100;
