-- Separate three effects that are often confused:
--   1. warehouse size (X-Small versus Small),
--   2. the running warehouse's local table-data cache, and
--   3. Snowflake's persisted query-result cache.

USE ROLE PERFORMANCE_ENGINEER;
USE DATABASE PERFORMANCE_LAB;
USE SCHEMA BENCHMARKS;
USE WAREHOUSE PERF_TEST_WH;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;

-- X-Small: first run after resume is cold; the identical second run can reuse
-- table data cached by the running warehouse, but not the persisted result.
ALTER WAREHOUSE PERF_TEST_WH SUSPEND;
ALTER WAREHOUSE PERF_TEST_WH SET WAREHOUSE_SIZE = 'XSMALL';
ALTER WAREHOUSE PERF_TEST_WH RESUME;

SELECT /* CH07_SIZE_AND_DATA_CACHE */
  L_RETURNFLAG,
  L_LINESTATUS,
  SUM(L_QUANTITY) AS SUM_QTY,
  SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
  SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
  AVG(L_QUANTITY) AS AVG_QTY,
  COUNT(*) AS LINE_COUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
WHERE L_SHIPDATE <= DATE '1998-09-02'
GROUP BY L_RETURNFLAG, L_LINESTATUS
ORDER BY L_RETURNFLAG, L_LINESTATUS;

INSERT INTO BENCHMARKS.RUN_LOG (EXPERIMENT, RUN_LABEL, QUERY_ID, NOTES)
SELECT 'WAREHOUSE_AND_CACHE', 'XS_COLD', LAST_QUERY_ID(),
       'X-Small first run after resume; result reuse disabled';

SELECT /* CH07_SIZE_AND_DATA_CACHE */
  L_RETURNFLAG,
  L_LINESTATUS,
  SUM(L_QUANTITY) AS SUM_QTY,
  SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
  SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
  AVG(L_QUANTITY) AS AVG_QTY,
  COUNT(*) AS LINE_COUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
WHERE L_SHIPDATE <= DATE '1998-09-02'
GROUP BY L_RETURNFLAG, L_LINESTATUS
ORDER BY L_RETURNFLAG, L_LINESTATUS;

INSERT INTO BENCHMARKS.RUN_LOG (EXPERIMENT, RUN_LABEL, QUERY_ID, NOTES)
SELECT 'WAREHOUSE_AND_CACHE', 'XS_WARM', LAST_QUERY_ID(),
       'X-Small second run; result reuse disabled, warehouse remains running';

-- Small: suspending before resizing removes the previous warehouse-cache state.
-- Compare cold with cold and warm with warm; do not compare XS_WARM to SMALL_COLD.
ALTER WAREHOUSE PERF_TEST_WH SUSPEND;
ALTER WAREHOUSE PERF_TEST_WH SET WAREHOUSE_SIZE = 'SMALL';
ALTER WAREHOUSE PERF_TEST_WH RESUME;

SELECT /* CH07_SIZE_AND_DATA_CACHE */
  L_RETURNFLAG,
  L_LINESTATUS,
  SUM(L_QUANTITY) AS SUM_QTY,
  SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
  SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
  AVG(L_QUANTITY) AS AVG_QTY,
  COUNT(*) AS LINE_COUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
WHERE L_SHIPDATE <= DATE '1998-09-02'
GROUP BY L_RETURNFLAG, L_LINESTATUS
ORDER BY L_RETURNFLAG, L_LINESTATUS;

INSERT INTO BENCHMARKS.RUN_LOG (EXPERIMENT, RUN_LABEL, QUERY_ID, NOTES)
SELECT 'WAREHOUSE_AND_CACHE', 'SMALL_COLD', LAST_QUERY_ID(),
       'Small first run after resize and resume; result reuse disabled';

SELECT /* CH07_SIZE_AND_DATA_CACHE */
  L_RETURNFLAG,
  L_LINESTATUS,
  SUM(L_QUANTITY) AS SUM_QTY,
  SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
  SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
  AVG(L_QUANTITY) AS AVG_QTY,
  COUNT(*) AS LINE_COUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
WHERE L_SHIPDATE <= DATE '1998-09-02'
GROUP BY L_RETURNFLAG, L_LINESTATUS
ORDER BY L_RETURNFLAG, L_LINESTATUS;

INSERT INTO BENCHMARKS.RUN_LOG (EXPERIMENT, RUN_LABEL, QUERY_ID, NOTES)
SELECT 'WAREHOUSE_AND_CACHE', 'SMALL_WARM', LAST_QUERY_ID(),
       'Small second run; inspect percentage scanned from cache in Query Profile';

-- Persisted result cache: this pair has a query text not used above. The first
-- statement executes; the byte-for-byte identical second statement should be
-- returned from persisted results when Snowflake's reuse conditions are met.
ALTER SESSION SET USE_CACHED_RESULT = TRUE;

SELECT /* CH07_PERSISTED_RESULT_CACHE */
  L_RETURNFLAG,
  L_LINESTATUS,
  SUM(L_QUANTITY) AS SUM_QTY,
  SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
  SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
  AVG(L_QUANTITY) AS AVG_QTY,
  COUNT(*) AS LINE_COUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
WHERE L_SHIPDATE <= DATE '1998-09-02'
GROUP BY L_RETURNFLAG, L_LINESTATUS
ORDER BY L_RETURNFLAG, L_LINESTATUS;

INSERT INTO BENCHMARKS.RUN_LOG (EXPERIMENT, RUN_LABEL, QUERY_ID, NOTES)
SELECT 'RESULT_CACHE', 'RESULT_CACHE_POPULATE', LAST_QUERY_ID(),
       'First execution of unique query text with result reuse enabled';

SELECT /* CH07_PERSISTED_RESULT_CACHE */
  L_RETURNFLAG,
  L_LINESTATUS,
  SUM(L_QUANTITY) AS SUM_QTY,
  SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
  SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
  AVG(L_QUANTITY) AS AVG_QTY,
  COUNT(*) AS LINE_COUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
WHERE L_SHIPDATE <= DATE '1998-09-02'
GROUP BY L_RETURNFLAG, L_LINESTATUS
ORDER BY L_RETURNFLAG, L_LINESTATUS;

INSERT INTO BENCHMARKS.RUN_LOG (EXPERIMENT, RUN_LABEL, QUERY_ID, NOTES)
SELECT 'RESULT_CACHE', 'RESULT_CACHE_REUSE', LAST_QUERY_ID(),
       'Identical statement; expect no physical operator tree if result reused';

-- Restore the inexpensive default
ALTER WAREHOUSE PERF_TEST_WH SET WAREHOUSE_SIZE = 'XSMALL';
