-- Chapter 2: DDL and DML workshop
-- Create the objects used by this workshop.

CREATE DATABASE IF NOT EXISTS SQL_IN_SNOWFLAKE;
CREATE SCHEMA IF NOT EXISTS SQL_IN_SNOWFLAKE.DML_DDL;

USE DATABASE SQL_IN_SNOWFLAKE;
USE SCHEMA DML_DDL;

CREATE OR REPLACE FILE FORMAT WORKSHOP_CSV_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE DML_DDL_STAGE
  FILE_FORMAT = WORKSHOP_CSV_FORMAT;

CREATE TABLE IF NOT EXISTS PRODUCTS (
  PRODUCT_ID NUMBER(10, 0),
  PRODUCT_NAME VARCHAR,
  CATEGORY VARCHAR,
  UNIT_PRICE NUMBER(10, 2),
  IS_ACTIVE BOOLEAN,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS INVENTORY_ADJUSTMENTS (
  ADJUSTMENT_ID NUMBER(10, 0),
  PRODUCT_ID NUMBER(10, 0),
  QUANTITY_CHANGE NUMBER(10, 0),
  REASON VARCHAR,
  ADJUSTED_ON DATE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
