-- Chapter 2: DDL and DML workshop
-- DML inserts, changes, deletes, and combines table rows.

USE DATABASE SQL_IN_SNOWFLAKE;
USE SCHEMA DML_DDL;

-- 1. INSERT: add a product only when it is not already present.
-- The NOT EXISTS guard makes this example safe to run again.
INSERT INTO PRODUCTS (
  PRODUCT_ID,
  PRODUCT_NAME,
  CATEGORY,
  UNIT_PRICE,
  IS_ACTIVE
)
SELECT
  NEW_PRODUCT.PRODUCT_ID,
  NEW_PRODUCT.PRODUCT_NAME,
  NEW_PRODUCT.CATEGORY,
  NEW_PRODUCT.UNIT_PRICE,
  NEW_PRODUCT.IS_ACTIVE
FROM VALUES (1005, 'Laptop Stand', 'Accessories', 39.99, TRUE)
  AS NEW_PRODUCT(PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE, IS_ACTIVE)
WHERE NOT EXISTS (
  SELECT 1
  FROM PRODUCTS AS P
  WHERE P.PRODUCT_ID = NEW_PRODUCT.PRODUCT_ID
);

-- 2. UPDATE: correct a value in an existing row.
UPDATE PRODUCTS
SET UNIT_PRICE = 79.99
WHERE PRODUCT_ID = 1002;

-- 3. INSERT an adjustment used only to demonstrate DELETE.
INSERT INTO INVENTORY_ADJUSTMENTS (
  ADJUSTMENT_ID,
  PRODUCT_ID,
  QUANTITY_CHANGE,
  REASON,
  ADJUSTED_ON
)
SELECT 9999, 1001, 1, 'temporary training record', CURRENT_DATE()
WHERE NOT EXISTS (
  SELECT 1
  FROM INVENTORY_ADJUSTMENTS
  WHERE ADJUSTMENT_ID = 9999
);

-- 4. DELETE: remove the temporary training record.
DELETE FROM INVENTORY_ADJUSTMENTS
WHERE ADJUSTMENT_ID = 9999;

-- 5. MERGE combines an update and an insert in one statement.
MERGE INTO PRODUCTS AS TARGET
USING (
  SELECT
    COLUMN1::NUMBER(10, 0) AS PRODUCT_ID,
    COLUMN2::VARCHAR AS PRODUCT_NAME,
    COLUMN3::VARCHAR AS CATEGORY,
    COLUMN4::NUMBER(10, 2) AS UNIT_PRICE,
    COLUMN5::BOOLEAN AS IS_ACTIVE
  FROM VALUES
    (1003, 'USB-C Dock', 'Accessories', 119.00, TRUE),
    (1006, 'Cable Organizer', 'Accessories', 14.50, TRUE)
) AS SOURCE
ON TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
  TARGET.PRODUCT_NAME = SOURCE.PRODUCT_NAME,
  TARGET.CATEGORY = SOURCE.CATEGORY,
  TARGET.UNIT_PRICE = SOURCE.UNIT_PRICE,
  TARGET.IS_ACTIVE = SOURCE.IS_ACTIVE
WHEN NOT MATCHED THEN INSERT (
  PRODUCT_ID,
  PRODUCT_NAME,
  CATEGORY,
  UNIT_PRICE,
  IS_ACTIVE
) VALUES (
  SOURCE.PRODUCT_ID,
  SOURCE.PRODUCT_NAME,
  SOURCE.CATEGORY,
  SOURCE.UNIT_PRICE,
  SOURCE.IS_ACTIVE
);

SELECT
  PRODUCT_ID,
  PRODUCT_NAME,
  CATEGORY,
  UNIT_PRICE,
  IS_ACTIVE,
  REORDER_POINT
FROM PRODUCTS
ORDER BY PRODUCT_ID;

-- 6. TRUNCATE removes every row from a table. Use a scratch table so the
-- workshop data remains available.
CREATE OR REPLACE TRANSIENT TABLE DML_SCRATCH AS
SELECT PRODUCT_ID, PRODUCT_NAME
FROM PRODUCTS;

SELECT COUNT(*) AS rows_before_truncate
FROM DML_SCRATCH;

TRUNCATE TABLE DML_SCRATCH;

SELECT COUNT(*) AS rows_after_truncate
FROM DML_SCRATCH;

DROP TABLE DML_SCRATCH;

-- 7. An explicit transaction lets several DML statements succeed or fail as a
-- unit. The following changes are visible in this session before ROLLBACK,
-- then discarded. Do not put DDL inside this transaction.
BEGIN TRANSACTION;

INSERT INTO INVENTORY_ADJUSTMENTS (
  ADJUSTMENT_ID,
  PRODUCT_ID,
  QUANTITY_CHANGE,
  REASON,
  ADJUSTED_ON
)
VALUES (9998, 1001, -1, 'transaction rollback example', CURRENT_DATE());

SELECT *
FROM INVENTORY_ADJUSTMENTS
WHERE ADJUSTMENT_ID = 9998;

ROLLBACK;

-- Confirm that the transaction's adjustment was not committed.
SELECT *
FROM INVENTORY_ADJUSTMENTS
WHERE ADJUSTMENT_ID = 9998;
